server:
  port: 9000

logging:
  level:
    org:
      springframework:
        security: TRACE
        oauth2: TRACE

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account-app-db?createDatabaseIfNotExist=true
    username: root
    password: 12345
    driverClassName: com.mysql.cj.jdbc.Driver

  sql:
    init:
      schema-locations:
        - 'classpath:org/springframework/security/oauth2/server/authorization/client/oauth2-registered-client-schema.sql'
        - 'classpath:org/springframework/security/oauth2/server/authorization/oauth2-authorization-consent-schema.sql'
        - 'classpath:org/springframework/security/oauth2/server/authorization/oauth2-authorization-schema.sql'

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

#JWT keys confuguration
jwt:
  key:
    id: 'c90ef912-32b2-464c-8746-934e0caf6c95'
    public: classpath:app.pub
    private: classpath:app.key